// react-app/src/components/calendar.jsx
import React, { Component } from "react";
import classNames from "classnames/bind";
import _ from "lodash";

const DAYS = _.range(1, 32).map(day => "Oct " + day);

function randomMilliseconds() {
  return Math.floor(Math.random() * 500);
}

const service = {
  cells: [],
  addCell(cell) {
    this.cells.push(cell);
  },
  searchAllCells() {
    for (let i = 0; i < this.cells.length; i++) {
      this.cells[i].search();
    }
  }
};

class Cell extends Component {
  constructor(props) {
    super(props);

    this.search = this.search.bind(this);
    this.clicked = this.clicked.bind(this);

    this.state = {
      isSearching: false,
      searchResults: null
    };

    service.addCell(this);
  }

  render() {
    if (this.state.isSearching) {
      return (
        <td className="hour-cell">
          <div className="searching">...</div>
        </td>
      );
    } else if (this.state.searchResults) {
      var options = this.state.searchResults.options;
      var classes = classNames({
        "good-results": options > 3,
        "weak-results": options > 1 && options <= 3,
        "bad-results": options >= 0 && options <= 1
      });

      return (
        <td className="hour-cell" onClick={this.clicked}>
          <div className={classes}>
            <div>{this.state.searchResults.options}</div>
            <div className="result-label">results</div>
          </div>
        </td>
      );
    } else {
      return (
        <td className="hour-cell" onClick={this.clicked}>
          <div className="time">{this.props.hour}:00</div>
        </td>
      );
    }
  }

  clicked() {
    this.search();
  }

  search() {
    this.setState({
      isSearching: true,
      searchResults: { options: null }
    });

    setTimeout(() => {
      this.setState({
        isSearching: false,
        searchResults: { options: Math.floor(Math.random() * 5) }
      });
    }, randomMilliseconds());
  }
}

class Calendar extends Component {
  constructor(props) {
    super(props);

    this.load = this.load.bind(this);
    this.searchAll = this.searchAll.bind(this);

    this.state = {
      isLoaded: false
    };
  }

  render() {
    return (
      <div>
        {this.state.isLoaded || (
          <button className="btn" onClick={this.load}>
            Load
          </button>
        )}
        {this.state.isLoaded && (
          <button className="btn" onClick={this.searchAll}>
            Search all month
          </button>
        )}
        {this.state.isLoaded && (
          <table>
            <tbody>
              <tr>
                {DAYS.map((day, index) => (
                  <th
                    className="day-header"
                    onClick={this.clicked}
                    key={"th" + index}
                  >
                    {day}
                  </th>
                ))}
              </tr>
              {_.range(24).map((hour, index) => (
                <tr key={"tr" + index}>
                  {DAYS.map((day, index) => (
                    <Cell
                      hour={hour}
                      day={day}
                      key={day}
                      events={this.events}
                      key={"cell" + index}
                    />
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    );
  }

  load() {
    this.setState({ isLoaded: true });
  }

  searchAll() {
    service.searchAllCells();
  }
}

export default Calendar;

// vue-performance/src/components/Calendar.vue
<template>
  <div class="calendar">
    <button class="btn" v-if="!isLoaded" v-on:click="load">Load</button>
    <button class="btn" v-if="isLoaded" v-on:click="searchAll">Search all month</button>
    <table v-if="isLoaded">
      <tr>
        <th v-for="(day, key, index) in days" :key="index" class="day-header" @click="dayHeaderClicked(day)">
          {{day}}
        </th>
      </tr>
      <tr v-for="(hour, key, index) in hours" :key="index">
        <td v-for="(day, key, index) in days" :key="index" class="hour-cell">
          <CalendarCell v-bind:hour="hour" v-bind:day="day"/>
        </td>
      </tr>
    </table>
  </div>
</template>

<script>
import _ from "lodash";
import CalendarCell from "./CalendarCell";
import service from "../service";

export default {
  name: "Calendar",
  components: {
    CalendarCell
  },
  data() {
    return {
      hours: _.range(24),
      days: _.range(1, 32).map(day => "Oct " + day),
      isLoaded: false
    };
  },
  methods: {
    load() {
      this.isLoaded = true;
    },
    searchAll() {
      service.searchAllCells();
    },
    dayHeaderClicked() {
      alert("dayHeaderClicked()");
    }
  }
};
</script>

<style scoped>
/* table {
  border-right: 2px solid gray;
  border-spacing: 0;
  border-collapse: collapse;
}
.day-header {
  border: 1px solid gray;
  white-space: nowrap;
}
.day-header:hover {
  cursor: pointer;
}
.hour-cell:hover {
  background-color: #559 !important;
  color: white;
}
.hour-cell {
  width: 120px;
  text-align: center;
  border-left: 1px solid gray;
  border-bottom: 1px solid #eee;
  cursor: pointer;
  height: 30px;
  padding: 0;
}
.hour-cell > div {
  height: 100%;
}
.hour-cell .time {
  padding-top: 10px;
}
.hour-cell .searching {
  color: blue;
  font-size: 12px;
  padding-top: 12px;
}
.hour-cell .good-results {
  color: #090;
  background: #efffef;
}
.hour-cell .weak-results {
  color: orange;
  background: #ffffef;
}
.hour-cell .bad-results {
  color: red;
  background: #ffefef;
} */
</style>
